name: Py36Sci
channels:
- defaults
- conda-forge
dependencies:
- python-crfsuite=0.9.2=py36_0
- decorator=4.0.11=py36_0
- libgfortran=3.0.0=1
- mkl=2017.0.1=0
- networkx=1.11=py36_0
- numpy=1.13.0=py36_0
- openssl=1.0.2l=0
- pandas=0.20.2=np113py36_0
- pip=9.0.1=py36_1
- python=3.6.1=2
- python-dateutil=2.6.0=py36_0
- pytz=2017.2=py36_0
- readline=6.2=2
- scikit-learn=0.18.1=np113py36_1
- scipy=0.19.0=np113py36_0
- setuptools=27.2.0=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- tqdm=4.14.0=py36_0
- wheel=0.29.0=py36_0
- xlrd=1.0.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - langid==1.1.6
  - pbr==2.0.0
  - stevedore==1.21.0
  - virtualenv==15.1.0
  - virtualenv-clone==0.2.6
  - virtualenvwrapper==4.7.2
